# Generated by Django 3.2.7 on 2021-09-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='field_name',
            new_name='file_field_name',
        ),
        migrations.AddField(
            model_name='article',
            name='img_field_name',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
