# Generated by Django 3.2.7 on 2021-09-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210923_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file_field_name',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='pdfs/'),
        ),
    ]
